# Step 1: Use Node.js to build and run the React app
FROM node:22

WORKDIR /src

# Copy package.json and package-lock.json and install dependencies
COPY ./client/package.json ./client/package-lock.json ./
RUN npm install

# Copy the rest of the React app
COPY ./client ./

# Expose port 3000 (default for React dev server)
EXPOSE 3000

# Start the React development server
CMD ["npm", "run", "dev"]
