# Step 1: Use an official Node.js image
FROM node:22

WORKDIR /src
COPY ./server/package.json ./server/package-lock.json ./
RUN npm install

RUN npm install -g nodemon

# Copy the rest of the Express app
COPY ./server ./

EXPOSE 3000
CMD ["nodemon", "src/index.js"]