# Step 1: Use an official Node.js image
FROM node:22

WORKDIR /app
COPY ./server/package.json ./server/package-lock.json ./
RUN npm install

# Copy the rest of the Express app
COPY ./server ./

EXPOSE 3000
CMD ["node", "src/index.js"]